image: gitpod/workspace-full

tasks:
  - before: sdk env install && brew tap auth0/auth0-cli
    command: brew install auth0 && brew install httpie

vscode:
  extensions:
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-gradle
    - vscjava.vscode-maven
