image: gitpod/workspace-full

tasks:
  - before: sdk env install
    init: brew tap auth0/auth0-cli && brew install auth0
    command: brew install httpie

vscode:
  extensions:
    - pivotal.vscode-spring-boot
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-gradle
    - vscjava.vscode-maven
    - vscjava.vscode-graalvm
